### ISSUE TITLE
Is this necessary for `import/no-cycle`?

### ISSUE THREAD

**Issue by CMCDragonkai** [alexgorbatchev/eslint-import-resolver-typescript#106]
I came to this repo after this https://github.com/import-js/eslint-plugin-import#typescript says to also install this.

However I tried the rule `import/no-cycle`, and it worked as long as I added `plugin:import/typescript`:

```
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "plugin:import/typescript", // <--- ADDED THIS ONE
    "prettier"
  ],
  "plugins": [
    "import"
  ],
```

If I didn't have that plugin, it wouldn't work.

Now I checked my `package-lock.json` to see if something was bringing in this package `eslint-import-resolver-typescript`. But there was nothing.

```
[nix-shell:~/Projects/TypeScript-Demo-Lib-Native]$ ag 'eslint-import-resolver'
package-lock.json
2943:    "node_modules/eslint-import-resolver-node": {
2945:      "resolved": "https://registry.npmjs.org/eslint-import-resolver-node/-/eslint-import-resolver-node-0.3.6.tgz",
2953:    "node_modules/eslint-import-resolver-node/node_modules/debug": {
2994:        "eslint-import-resolver-node": "^0.3.6",
10529:    "eslint-import-resolver-node": {
10531:      "resolved": "https://registry.npmjs.org/eslint-import-resolver-node/-/eslint-import-resolver-node-0.3.6.tgz",
10581:        "eslint-import-resolver-node": "^0.3.6",
```

Does this mean this package isn't required for some of the rules in the `eslint-import-plugin`? Or should I still have this package for other reasons?

**Comment by JounQin** [comment]
You need enable this resovler manually, it helps to resolve `@types/*` automatically:

```json
{
  "import/resolver": {
    "typescript": {}
  }
}
```
