### ISSUE TITLE
import/no-unresolved error in v3.1.0

### ISSUE THREAD

**Issue by nightah** [alexgorbatchev/eslint-import-resolver-typescript#113]
It appears that some imports that previously did not have any issues with v2.7.1 now are throwing import/no-unresolved errors, specifically as follows:

```
/srv/repos/authelia/web/src/i18n/index.ts
  1:18  error  Unable to resolve path to module 'i18next'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)

file: /srv/repos/authelia/web/src/i18n/index.ts
error during build:
Error: 
/srv/repos/authelia/web/src/i18n/index.ts
  1:18  error  Unable to resolve path to module 'i18next'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

You can see the IDE also highlighting the same issue:

![image](https://user-images.githubusercontent.com/3339418/175875362-42ee8f48-ff7d-428a-9a75-767b011ac9a4.png)

Below is the consistent `.eslintrc.js` file utilised with both v2.7.1 and v3.1.0:

```js
module.exports = {
    parser: "@typescript-eslint/parser",
    parserOptions: {
        project: "tsconfig.json",
    },
    ignorePatterns: ["build/*", "coverage/*", "!.*.js"],
    settings: {
        "import/resolver": {
            typescript: {},
        },
    },
    extends: ["react-app", "plugin:import/errors", "plugin:import/warnings", "plugin:prettier/recommended", "prettier"],
    rules: {
        "import/order": [
            "error",
            {
                groups: ["builtin", "external", "internal"],
                pathGroups: [
                    {
                        pattern: "react",
                        group: "external",
                        position: "before",
                    },
                ],
                pathGroupsExcludedImportTypes: ["react"],
                "newlines-between": "always",
                alphabetize: {
                    order: "asc",
                    caseInsensitive: true,
                },
            },
        ],
    },
};
```

After some google-fu it appears I can resolve the issue by including the following extends for the eslint configuration:

```
"plugin:import/typescript"
```

I'm not really sure why this seems to resolve the issue, but I'm keen to understand why this has changed between the two versions and if it is perhaps some misconfiguration on my side.

It's worthwhile mentioning that I did also read the changelog and understandably with the major version bump there are breaking changes I'm just not sure what the expected action is if there's an adjustment that should be made to work alongside said breaking changes.

**Comment by JounQin** [comment]
3.0 is a major version, read CHANGELOG if you want to know what's changed.

**Comment by JounQin** [comment]
No breaking excepted but we did change the deps and support `exports` in `package.json`, so it's a major version.

Thanks for provide the reproduction link, I'll take a look later.

**Comment by JounQin** [comment]
This could be related to we support `exports` in `package.json` in v3.

**Comment by JounQin** [comment]
@nightah

`eslint-import-resolver-typescript@3.1.1` and `i18next@21.8.11` have just been released!

**Comment by nightah** [comment]
Thanks @JounQin, appreciate your assistance with this!
