### ISSUE TITLE
Version 1.1.x causes "Unable to resolve path to module" errors

### ISSUE THREAD

**Issue by JaredProske** [alexgorbatchev/eslint-import-resolver-typescript#15]
When I allow npm to upgrade this package beyond 1.0.2 I get the following error output:

> myfile.test.js
  1:1   error  Resolve error: Unexpected token )                                     import/no-unresolved
  1:1   error  Resolve error: Unexpected token )                                     import/no-extraneous-dependencies
  4:34  error  Unable to resolve path to module './myfile'  import/no-unresolved

where myfile is a typescript module and myfile.test is a javascript unit test file.

This is what my .eslintrc.json looks like 
```
{
    "parser": "babel-eslint",
    "env": {
        "jasmine": true,
        "es6": true,
        "browser": true,
        "node": true,
        "mocha": true
    },
    "settings": {
        "import/resolver": {
          "node": true,
          "eslint-import-resolver-typescript": true
        }
      },
    "plugins": ["jasmine", "react", "chai-friendly"],
    "extends": ["airbnb", "plugin:react/recommended"]
}
```
Let me know if you need more info.  We don't use webpack as this is a node app that serves static HTML via React components

**Comment by bradzacher** [comment]
- Does babel-eslint actually support typescript yet?

Regardless, unless you have an explicit need for the babel parser, I would suggest switching to [@typescript-eslint/parser](https://www.npmjs.com/package/@typescript-eslint/parser), it's built to properly integrate eslint and typescript.

- as per the readme, config with the new version should be:
```diff
 "settings": {
   "import/resolver": {
     "node": true,
-    "eslint-import-resolver-typescript": true
+    "typescript": {}
   }
 },
```

**Comment by JaredProske** [comment]
> Does babel-eslint actually support typescript yet?

I don't know actually.  We use tslint for for our typescript files and eslint for javascript. Come to think of it, I don't know why that is in there at all.  We don't use any language features in this project that would require it.  I can remove it and our linting works just fine.

If I update the config to match the readme I still get the same errors.
```
{
    "env": {
        "jasmine": true,
        "es6": true,
        "browser": true,
        "node": true,
        "mocha": true
    },
    "settings": {
        "import/resolver": {
          "node": true,
          "typescript": {}
        }
      },
    "plugins": ["jasmine", "react", "chai-friendly"],
    "extends": ["airbnb", "plugin:react/recommended"]
}
```

**Comment by bradzacher** [comment]
You need to use a typescript parser if you've got typescript code that will at some point be run through eslint.
ESLint has no concept of typescript language features, and its parser will crash on them.

Similarly eslint-plugin-import requires a typescript parser if you're importing typescript files.

What is your `myfile.test.js`? What is the imported file `'./myfile'`?
If you're only running eslint over your javascript code, how come you're using this plugin?

**Comment by JaredProske** [comment]
> What is your myfile.test.js? What is the imported file './myfile'?

The test file is importing the module under test like so:
`const myfile = require('../../src/myfile')`
`myfile` is typescript and exports some consts and a class like so
```
export const MY_CONST = '';
export class MyFileClass {}
```

> If you're only running eslint over your javascript code, how come you're using this plugin?

If we don't use this plugin then eslint does not know that the imported typescript class is a real module.  We get the "Unable to resolve path to module" error.  Adding this plugin (v1.0.2) fixed this  for us.

**Comment by JounQin** [comment]
If you're using `babel-eslint` with TypeScript together, make sure you're enabled TypeScript related babel plugin(s) correctly, close for now.

Please try the latest babel, or with babel-eslint@11.0.0-beta.0, or you should use `@typescript-eslint/parser` for `.tsx?` actually. Feel free to open a new issue if I'm incorrect.

**Comment by stoplion** [comment]
same issue 🫤

**Comment by bradzacher** [comment]
@stoplion please don't necro old, closed issue unless you have a solid repro or information to add.
