### ISSUE TITLE
import/no-unresolved when trying to import types from @types/*

### ISSUE THREAD

**Issue by manuelbieh** [alexgorbatchev/eslint-import-resolver-typescript#17]
I'm trying to use eslint with `@typescript-eslint/parser` and `eslint-plugin-import` but no matter what I do, I get an error:
```
Unable to resolve path to module 'express-serve-static-core'  import/no-unresolved
```
whenever I try to import types from `@types` packages.

Looks like the `sourceType: 'module'` parserOption is causing this error but when I remove it I get another error:
```
Parsing error: ImportDeclaration should appear when the mode is ES6 and in the module context
```

I created a minimal example to reproduce this error. Probably it's just a setting that's wrong but I have tried different settings, plugins, parserOptions and what not and I just don't get it working:
https://github.com/manuelbieh/eslint-typescript-import-bug

So I'm not sure if the problem is on my side or if it is a bug in this package.

**Comment by benmosher** [comment]
Ah, sweet, you beat me to this. was going to open a similar issue and link to https://github.com/benmosher/eslint-plugin-import/issues/1341#issuecomment-488271993

FWIW I'd call this an enhancement request and not a bug. But I am relatively new to the TS ecosystem so maybe there's an argument for calling this a bug.

Either way, I think it'd be straightforward to try a resolution against `@types/{whatever}` if no `ts` files are found at `{whatever}`.

**Comment by JounQin** [comment]
For anything maybe interested, you can try `eslint-import-resolver-typescript@JounQin/node_modules#eslint-import-resolver-typescript` temporarily (PR made at https://github.com/alexgorbatchev/eslint-import-resolver-typescript/pull/20).

**Comment by JounQin** [comment]
Try https://github.com/rx-ts/eslint-import-resolver-ts instead.

**Comment by femmor** [comment]
> Try https://github.com/rx-ts/eslint-import-resolver-ts instead.

This worked for me. Thanks

**Comment by JounQin** [comment]
@femmor This should be unnecessary, that plugin has been merged into this upstream project already.
