### ISSUE TITLE
[FEAT] Multiple tsconfig.json support

### ISSUE THREAD

**Issue by Teoxoy** [alexgorbatchev/eslint-import-resolver-typescript#21]
I am currently working on a yarn workspaces monorepo with one eslint config file at the root.
`@typescript-eslint/parser` supports multiple eslint configs trough `parserOptions.projects`

I am not sure if this can be automated (i.e. the plugin reads `parserOptions.projects`)

**Comment by mrmckeb** [comment]
I've just hit this too, it would be great to have.

**Comment by Teoxoy** [comment]
Check out: [ eslint-import-resolver-ts](https://github.com/rx-ts/eslint-import-resolver-ts)

**Comment by factoidforrest** [comment]
btw if anyone stumbles upon this like I did, it's natively supported now, just pass an array of projects in parserOptions

**Comment by JounQin** [comment]
@factoidforrest `parserOptions.project` is for `@typescript-eslint/eslint-parser`, `settings['import/resolvers'].typescript.project` is for this resolver.

**Comment by Voyager-Two** [comment]
For anyone else that stumbles upon this, add this to eslint config file:

```javascript
  settings: {
    "import/resolver": {
      "typescript": {
        "project": ["tsconfig.json", "src/client/tsconfig.json"]
      },
    }
  },
```
