### ISSUE TITLE
[RFC] Rename directory option to tsconfigPath or project

### ISSUE THREAD

**Issue by teoxoy** [alexgorbatchev/eslint-import-resolver-typescript#23]
Coming from dividab/tsconfig-paths#91, `tsconfigPaths.loadConfig(path)` accepts a file path too not only a directory.

I think the `directory` option should be renamed to something more descriptive. I have 2 alternatives in mind:

- `tsconfigPath`
- `project` - will keep things consistent with `@typescript-eslint/parser` (`parserOptions.project`) - but it's in no way as descriptive as `tsconfigPath`

This will be a breaking change!

**Comment by JounQin** [comment]
Let's waiting for the original issue first.

**Comment by Teoxoy** [comment]
The conclusion of the original issue is that `@typescript-eslint/parser` will stick to using `project`.
Do we want to change `directory` to `project`?
