### ISSUE TITLE
Broken with Jest

### ISSUE THREAD

**Issue by drewlustro** [alexgorbatchev/eslint-import-resolver-typescript#24]
### 🏳️ Waving a white flag for help here  

I have a fully passing `eslint` test suite/configuration. `yarn run eslint '**/*.ts*'` works handsomely.

Upon tooling the project to leverage a runner (`jest-runner-eslint`), the suite blows up. Hundreds of failures are logged:

`Resolve error: webpack with invalid interface loaded as resolver`

Errors like this, I recall, were solved after I added `eslint-import-resolver-typescript` to my project. This leads me to believe that something is busted in the way Jest loads `.eslintrc.js` or uses this module.

Has anyone else experienced this issue?

**Comment by JounQin** [comment]
Invalid issue without any detail information, close for now.

Please provide a minimal runnable reproduction next time.
