### ISSUE TITLE
Unable to resolve path to module for .jsx files

### ISSUE THREAD

**Issue by pekala** [alexgorbatchev/eslint-import-resolver-typescript#25]
Seems that currently files with `.jsx` extension are not supported by the resolver. 

This list of extensions: 

https://github.com/alexgorbatchev/eslint-import-resolver-typescript/blob/18eafa26db7cee5fcdbccfe211d1c412a1e899b9/index.js#L28-L32

does not cover `.jsx`. Adding it, fixed the issue for me. Would this be an acceptable fix? I can prepare a PR.

**Comment by JounQin** [comment]
Are you using `allowJs` with `.jsx`?

You can create PR to https://github.com/rx-ts/eslint-import-resolver-ts/blob/master/src/index.ts#L17 which is a fork and enhacer for it.

**Comment by JounQin** [comment]
@pekala PR welcome.
