### ISSUE TITLE
directory starting with a dot does not work

### ISSUE THREAD

**Issue by jirutka** [alexgorbatchev/eslint-import-resolver-typescript#30]
The following example:

```json
{
  "settings": {
    "import/resolver": {
      "typescript": {
        "directory": "./packages/*/tsconfig.json"
      }
    }
  }
}
```

doesn’t work, `globSync()` (from tiny-glob) resolves nothing. It works without the leading `./`, i.e. `packages/*/tsconfig.json`.

(I spent an hour trying to figure out why the heck I’m still getting unresolved import errors even after changing my configuration to exactly match the examples. :frowning_face:)

**Comment by JounQin** [comment]
Hmmm... Sorry about that, maybe we should post another to `tiny-glob` instead.
