### ISSUE TITLE
Version 2 release missing on GitHub

### ISSUE THREAD

**Issue by CodingDive** [alexgorbatchev/eslint-import-resolver-typescript#32]
Hey, thank you for all the work on this wonderful plugin.

I saw that after https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/29 was resolved, version 2 was published to [npm](https://www.npmjs.com/package/eslint-import-resolver-typescript) 🎉 

I couldn't find the release on [GitHub](https://github.com/alexgorbatchev/eslint-import-resolver-typescript/releases) which lists version 1.1.1 as the latest release and could also not find a changelog file. This makes me uncomfortable bumping to new major version as I'm running a very complex unejected CRA setup which I really don't want to break again. :grin:

Could you provide some information on the breaking change(s)?

**Comment by JounQin** [comment]
https://github.com/rx-ts/eslint-import-resolver-ts/blob/master/CHANGELOG.md

It should be same.

**Comment by CodingDive** [comment]
Am I missing something? The forked project you linked has completely
different versions and another name.

I'm curious about v2 of eslint-import-resolver-typescript.

**Comment by JounQin** [comment]
I mean the changelog content is same. I forked it a few days ago and haven't PR back into 2.0.

**Comment by JounQin** [comment]
https://github.com/alexgorbatchev/eslint-import-resolver-typescript/releases/tag/v2.0.0
