### ISSUE TITLE
import/order generates wrong order with 2.0

### ISSUE THREAD

**Issue by Evalon** [alexgorbatchev/eslint-import-resolver-typescript#34]
After upgrade to resolver 2.0 import/order plugin starts generate wrong order for files that locally redefined.
For example: styled-components recommend use declaration merging (https://www.styled-components.com/docs/api#create-a-declarations-file) for use theme in styled.
Before version 2.0 this imports (e.g` import styled from 'styled-components'`) was "external" but now it's "local". This is prevent me to upgrade to version 2.0.

**Comment by JounQin** [comment]
You should post issue at `eslint-plugin-import` instead.

Related: https://github.com/rx-ts/eslint-import-resolver-ts/issues/14#issuecomment-536522805

**Comment by aequasi** [comment]
How would i change the order so @paths imports show above relative imports?

**Comment by JounQin** [comment]
> How would i change the order so @paths imports show above relative imports?

@aequasi Sorry, but I have no idea what's your point. If you got any problem, please raise another issue with a minimal runnable reproduction please.
