### ISSUE TITLE
Typescript Paths still unresolved for sub-folders config

### ISSUE THREAD

**Issue by n44ps** [alexgorbatchev/eslint-import-resolver-typescript#36]
Hello, 

I'm trying to use React, Eslint, Typescript, Airbnb Config.
I want to use typescript `paths`, here `@components`.
The problem is that **it works** at the **root** of the project, but **not** using **sub-folders**.
The examples uses the structure of a **monorepo** using `packages` folder.

Packages are : 

```
    "@typescript-eslint/eslint-plugin": "^2.7.0",
    "@typescript-eslint/parser": "^2.7.0",
    "eslint": "^6.6.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0"
```

Here is a reproduction : https://github.com/n44ps/eslint-import-resolver-typescript-repro/

Thank you for your help !

n44ps

**Comment by JounQin** [comment]
What's the error message outputs?

Can you run `eslint . --debug` and paste the output message here?

**Comment by JounQin** [comment]
And I think you don't need to provide `https://github.com/n44ps/eslint-import-resolver-typescript-repro/blob/master/packages/web/.eslintrc.js` which is redundant.

**Comment by JounQin** [comment]
And you've not set `"directory": "packages/*/tsconfig.json"` like the example in `README`.

So, seems an invalid usage, feel free to point out me if I'm wrong.

Closing for now.

**Comment by n44ps** [comment]
This is what I get for `eslint . --debug` [result.txt](https://github.com/alexgorbatchev/eslint-import-resolver-typescript/files/3854347/result.txt).

I removed `packages/web/.eslintrc.js` but still not working, and I tried to update the `./eslintrc.js` with :

```
            "typescript": {
                "directory": "./packages/*/tsconfig.json"
            }
```

But still not working :(

**Comment by n44ps** [comment]
I just updated the https://github.com/n44ps/eslint-import-resolver-typescript-repro/ with your advice, still the same.

**Comment by JounQin** [comment]
@n44ps Can you try `eslint . --ext ts,tsx`?

**Comment by n44ps** [comment]
Yes, did that : 

```
yarn lint . --ext ts,tsx
yarn run v1.19.1
$ eslint . --ext ts,tsx
/Users/florianmichaut/Projects/eslint/src/index.tsx
  2:32  error  Unable to resolve path to module '@components'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```

**Comment by JounQin** [comment]
OK, Let me have a look, wait for a while.

**Comment by JounQin** [comment]
@n44ps It should be `"directory": ["tsconfig.json", "packages/*/tsconfig.json"]`

**Comment by n44ps** [comment]
Well, I forgot the `tsconfig.json` in the root, so I updated `.eslintrc.js` with :

```
            "typescript": {
                "directory": ["packages/*/tsconfig.json", "tsconfig.json"]
            }
```

And now it works :

```
yarn lint . --ext ts,tsx
yarn run v1.19.1
$ eslint . --ext ts,tsx
✨  Done in 2.76s.
```

What I don't understand is why VSCode is still complaining : 

<img width="1552" alt="Capture d’écran 2019-11-16 à 16 34 20" src="https://user-images.githubusercontent.com/1702207/68995502-02e30780-088f-11ea-9ddd-832643d544a3.png">

Would you have an idea why ? I only have Eslint Plugin in VSCode.

Thank you !

**Comment by JounQin** [comment]
May you should reload VScode. Somethings, vscode-eslint is stupid event configurations changed.

**Comment by JounQin** [comment]
Next time, you can provide reproduction with something like [gitpod](https://f930ee42-3608-4282-8633-397d18fb1f27.ws-ap01.gitpod.io/#/workspace/eslint-import-resolver-typescript-repro).

**Comment by n44ps** [comment]
Indeed tried new configuration using`eslint.workingDirectories` but after many reload it started to work.
I lost at least a whole day on this issue :( Thank you again for your patience and your answers, and thanks for the discovery of Gitpod :)

Have a nice day / night !

**Comment by JounQin** [comment]
Good night from me. :)

**Comment by dardanos** [comment]
> `vscode-eslint` is stupid even configurations changed.

That comment made my day hahaha
![](https://media.giphy.com/media/12msOFU8oL1eww/giphy.gif)
