### ISSUE TITLE
[import/no-unresolved] not working in our mono-repo from 2.0.0

### ISSUE THREAD

**Issue by rheaditi** [alexgorbatchev/eslint-import-resolver-typescript#37]
We recently upgraded to Typescript 3.7 and updated all eslint + prettier related packages. Moving from `eslint-import-resolver-typescript@1.1.1` to `eslint-import-resolver-typescript@2.0.0` is leading to more `import/no-unresolved` errors showing up for `paths` configured in `tsconfig.json` in the sub-packages.

## Our structure

```sh
.
├── ...
├── .eslintrc.js
├── packages
│   ├── a
│   │   ├── .eslintrc.js
│   │   ├── tsconfig.json
│   │   └── package.json
│   └── b
│       ├── .eslintrc.js
│       ├── tsconfig.json
│       └── package.json
├── ...
├── package.json
├── lerna.json
```

We're using multiple `.eslintrc.js` in each directory since the projects are cross platform (node/browser) and have different environments & configurations.

## Configs

```js
// .eslintrc.js
module.exports = {
  // ...
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: ['import'],
  rules: {
    // ...
    /** Show errors for un-resolved imports */
    'import/no-unresolved': 'error',
    // ...
  },
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: {
        directory: ['packages/*/tsconfig.json'],
      },
    },
  },
};
```

```js
// .eslintrc.js
const { resolve } = require('path');

module.exports = {
  settings: {
    'import/resolver': {
      typescript: {
        directory: resolve(__dirname, 'tsconfig.json'),
      },
    },
  },
};
```
## What we've tried

* Having a single setting in the root level with `packages/*/tsconfig.json`
* Having a single setting in the root level with array of actual file paths to the tsconfig directory.
* Both the above with explicit setting in the package (a/b) level setting with directory: resolve(__dirname, 'tsconfig.json'),

---

We downgraded back to `v1.1.1`. 😅 

Can you help us out? Happy to provide more information as required.

**Comment by JounQin** [comment]
Please provide a minimal runnable reproduction, thx.

**Comment by JounQin** [comment]
Personal idea without approve, you should never use multiple `.eslintrc.js` files, replace them with `overrides` instead.

Take https://github.com/1stG/configs/tree/master/packages/eslint-config as an example.

Feel free to point out if I'm wrong.

**Comment by JounQin** [comment]
Or try to add `root: true` in every `.eslintrc.js` so that the root level eslint will not try to resolve paths any more.

**Comment by ZmoNkk** [comment]
I have possibly encountered the same problem:

Whenever you run eslint on several files from different sub-packages `import-unresolved` errors  show up, but running on single file is always OK.  

Please check this repo for reproduction: https://github.com/ZmoNkk/import-resolver-typescript-demo

### Repro steps: 
1. Install eslint and all dependencies
2. Run `./node_modules/.bin/eslint a/index.ts`.
3. As expected it shows only one error regarding non existing package.
4. Run `./node_modules/.bin/eslint --ext .ts ./`

#### Result:

First file is linted ok, but second file throws `import/no-unresolved` error on exising package.

Any advice? Possibly this is a misconfiguration on my part, but I have tried different setups and this issue persists. 

Issue does not appear on `v1.1.1` as well

**Comment by JounQin** [comment]
@ZmoNkk Thx for reproduction, I'll check it ASAP when I'm not so busy.

**Comment by JounQin** [comment]
@ZmoNkk Please check https://github.com/ZmoNkk/import-resolver-typescript-demo/pull/1/files. I believe you're both misusing `eslint` with `eslint-import-resolver-typescript`.

I'll close this issue temporarily, feel free to point out me and I'll reopen it.

**Comment by towry** [comment]
I have below config in `.eslintrc.yml` and the vscode + volar give me following error: 

config:

```yml
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  createDefaultProgram: true
  project:
    - ./tsconfig.json
```

error:

```
Parsing error: Cannot read file '/users/xxx/workspace/monorepo-proj/tsconfig.json'
```

And the project folder structure is:

```
--- monorepo-proj
   --- apps/demo
         --- apps/demo/.eslintrc.yml
```
