### ISSUE TITLE
Is my custom eslint shareable config good like this or should I change it?

### ISSUE THREAD

**Issue by rfgamaral** [alexgorbatchev/eslint-import-resolver-typescript#38]
I have created this[ shareable ESLint configuration](https://github.com/rfgamaral/eslint-config-typescript-unified) and I'm wondering if the following:

```js
module.exports = {
    settings: {
        'import/resolver': {
            typescript: {
                alwaysTryTypes: false,
            },
        },
    },
};
```

Is the same as:

```js
module.exports = {
    settings: {
        'import/resolver': {
            typescript: {},
        },
    },
};
```

?

If not, could you be so kind in explaining the differences? Should I change [this](https://github.com/rfgamaral/eslint-config-typescript-unified/blob/master/airbnb.js#L13)?

**Comment by JounQin** [comment]
@rfgamaral They're same anyway. But I'm using `alwaysTryTypes: true` always personally, because I'm also a maintainer of `mdx` now, and there is not related original package for `@types/unist`.

For sharable configuration, you can check the source codes of https://github.com/1stG/configs/tree/master/packages/eslint-config as reference.

**Comment by rfgamaral** [comment]
@JounQin I asked because I'm having a similar issue to #37 and I can't understand what's wrong with my configuration. I thought I could be doing something wrong with my ESLint config package.

I'll try to create a minimal reproducible repository tomorrow and post on the other issue, maybe you can understand what I'm doing wrong...

**Comment by JounQin** [comment]
@rfgamaral That's fibe. I'm wondering if my [PR](https://github.com/ZmoNkk/import-resolver-typescript-demo/pull/1/files) helps#

**Comment by rfgamaral** [comment]
> 
> 
> @rfgamaral That's fine. I'm wondering if my [PR](https://github.com/ZmoNkk/import-resolver-typescript-demo/pull/1/files) helps?

I looked at that but there are so many changes that I'm not sure what's the bit that actually fixes the problem...

**Comment by JounQin** [comment]
@rfgamaral The key difference is that we should only have one `.eslintrc` for all files. Of course, if you still have problems, feel free to provide another minimal reproduction, I'll try to help fixing them.

**Comment by rfgamaral** [comment]
@JounQin Actually, I'm not sure I have the same problem as #37. I mean, I get this error in VS Code with the ESLint extension: `Unable to resolve path to module '@tier-based-promotions/core'.eslint(import/no-unresolved)`, however, running the `eslint` tool in the CLI doesn't give me any errors at all.

Maybe **my** problem is actually in the ESLint extension and not the configuration...?

**Comment by JounQin** [comment]
@rfgamaral Sorry, no idea about this.

**Comment by rfgamaral** [comment]
> 
> 
> @rfgamaral Sorry, no idea about this.

That's fine, no worries. Thanks for your support :)

Anyway, I've [posted this](https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-564013256) if you're interested to follow up.
