### ISSUE TITLE
Reports false positives for deprecated methods

### ISSUE THREAD

**Issue by digeomel** [alexgorbatchev/eslint-import-resolver-typescript#44]
Not sure if this is a problem with the original import plugin or with this resolver, but I'm having this issue:

https://github.com/benmosher/eslint-plugin-import/issues/1532

**Comment by JounQin** [comment]
I think there is nothing related to `eslint-import-resolver-typescript` at all.

This resolver only resolves file path for `eslint-plugin-import`.
