### ISSUE TITLE
@typescript-eslint treats imports as any in second package

### ISSUE THREAD

**Issue by JakubKoralewski** [alexgorbatchev/eslint-import-resolver-typescript#53]
I have a project in the root directory, and a `packages` folder with some git submodules inside. I'm liniting using the same `.eslintrc.js` across all packages and the root with one config file that resides inside `packages/shared/.eslintrc.js`. I share this configuration across front-end and back-end.

Everything works great on the root directory, but inside `packages/some-package`, I am getting errors. I managed to fix it not recognizing the paths like `import SomeClass from 'path-import/subfolder/SomeClass'`, but when I instantiate or use that class I am getting some weird errors.

For example:
```ts
//packages/some-package/src/index.ts
import SomeClass from 'path-import/subfolder/SomeClass';
const instance = new SomeClass();
```
Gives me: `ESLint: Unsafe construction of an any type value.(@typescript-eslint/no-unsafe-call)`.

That happens across the whole `packages/some-package`, that when I import something from another file `@typescript-eslint` treats that type as an `any` type.

For example, when I have a class with a property:
```ts
//packages/some-package/src/path-import/subfolder/SomeClass';
import AnotherClass from 'path-import/another-subfolder/AnotherClass';
export default class SomeClass {
  public someProperty: AnotherClass;
  public someMethod() {
    return this.someProperty.xd;
  }
}
```

I will get `ESLint: Unsafe member access .xd on an any value.(@typescript-eslint/no-unsafe-member-access)`.
<details>
<summary>
.eslintrc.js
</summary>

```js
...
	'env': {
		'browser': true,
		'node': true
	},
	'extends': [
		'plugin:@typescript-eslint/recommended',
		'plugin:@typescript-eslint/recommended-requiring-type-checking'
	],
	'parser': '@typescript-eslint/parser',
	parserOptions: {
		// tsconfigRootDir: __dirname,
		project: 'packages/shared/tsconfig.eslint.json',
		'sourceType': 'module'
	},
	'plugins': [
		'@typescript-eslint',
		'import'
	],
	'settings': {
		'import/parsers': {
			'@typescript-eslint/parser': ['.ts', '.tsx']
		},
		'import/resolver': {
			'typescript': {
				'alwaysTryTypes': true // always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`
			}
		}
	},
...
```

</details>
<details>
<summary>
.eslintrc.frontend.js
</summary>

```js
module.exports = {
	'extends': [
		'plugin:react/recommended',
		'.eslintrc.js'
	],
	parserOptions: {
		ecmaFeatures: {
			jsx: true
		}
	},
	settings: {
		react: {
			version: 'detect'
		},
		'import/parsers': {
			'@typescript-eslint/parser': ['.ts', '.tsx']
		},
		'import/resolver': {
			// use <root>/tsconfig.json
			'typescript': {
				'directory': [
					'packages/*/tsconfig.json',
					__dirname
				],
				'alwaysTryTypes': true // always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`
			}
		}
	},
	'rules': {
		'react/no-unescaped-entities': 0,
		'react/display-name': 0,
	}
};
```

</details>

<details>
<summary>
package.json - frontend
</summary>
Then in `package.json` in the frontend:

```js
...
  "eslintConfig": {
    "extends": "./packages/shared/.eslintrc.react.js"
  },
...
```

</details>

<details>
<summary>
versions
</summary>

```json
//package.json
...
//"devDependencies"
    "@typescript-eslint/eslint-plugin": "^3.6.1",
    "@typescript-eslint/parser": "^3.6.1",
    "eslint": "^7.4.0",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-import": "^2.22.0",
...
```

</details>

**Comment by JounQin** [comment]
What makes think it is related to `eslint-import-resolver-typescript`? It seems just be related to `@typescript-eslint/eslint-plugin`?

**Comment by JakubKoralewski** [comment]
@JounQin Thanks for answering.

I assumed this, since it seems to only have problems with packages resolved by `eslint-import-resolver-typescript`. I guess if it's not this, then I don't know what's the problem. `@typescript-eslint/eslint-plugin` probably uses types that are provided to it, so to find the source of this bug I think I have to be looking for whatever generates the types resolved by the custom `tsconfig.compilerOptions.paths` property. I don't know what's responsible for this problem, sorry.

**Comment by JounQin** [comment]
`@typescript-eslint/eslint-plugin` has nothing related `eslint-plugin-import` at all.
