### ISSUE TITLE
New Feature - tsconfigrootdir

### ISSUE THREAD

**Issue by Ebooth** [alexgorbatchev/eslint-import-resolver-typescript#58]
Is it possible to add a new config parameter tsconfigRootDir so that the paths in the projects array are resolved relative to this parameter instead of cwd ? 
This is useful when you want to run eslint from a workspace instead of the root of the project.

The same has already been implemented for the typescript-eslint parser.
https://www.npmjs.com/package/@typescript-eslint/parser

**Comment by JounQin** [comment]
What do mean with

> The same has already been implemented for the typescript-eslint parser.

**Comment by Ebooth** [comment]
I mean that both @typescript-eslint/parser and eslint-import-resolver-typescript provide a "project" option to define the locations of the tsconfig files but @typescript-eslint/parser package allows us also to configurate how are resolved the paths provided in the "project" option with the "tsconfigRootDir" option.
I thought it could be nice to also have this option in the eslint-import-resolver-typescript

**Comment by JounQin** [comment]
I still can understand why this option is required, do you have any example that `project` won't work?

Fewer options is preferred IMO.

**Comment by evp3103** [comment]
If the configs are not in the root of the open project in the code editor, then you have to specify the current directory to fix the linting
```
parserOptions: {
  project: "./tsconfig.json",
  tsconfigRootDir: __dirname,
},
```
After that I have the same problem
> Unable to resolve path to module '@/components/...'.
To fix it you have to redefine the path to the ts config by adding the current directory to the path
```
"import/resolver": {
  typescript: {
    project: `${__dirname}/tsconfig.json`,
  },
},
```
Therefore, this parameter `tsconfigRootDir` is ignored

**Comment by JounQin** [comment]
So does `${__dirname}/tsconfig.json` work to you?

If it works, why you prefer `project` + `tsconfigRootDir`? It seems not making sense to me.

**Comment by JounQin** [comment]
Close due to inactive. Let me know if you want to discuss further.
