### ISSUE TITLE
Can't resolve path alias when wildcard is empty

### ISSUE THREAD

**Issue by juzerzarif** [alexgorbatchev/eslint-import-resolver-typescript#59]
I have the following paths config in my tsconfig.json
```json
{
  ...
  "baseUrl": ".",
  "paths": {
      "@jest-utils*": ["tests/jest/test-utils*", "tests/jest/test-utils/index"]
    }
}
```
and this in my .tsx file
```javascript
import { someFunc } from '@jest-utils'; // someFunc exported from tests/jest/test-utils/index
```

I get an eslint error from the import/no-unresolved rule but the typescript compiler can resolve the file just fine.
I don't get an eslint error for this:
```javascript
import { someOtherFunc } from '@jest-utils/some-dir';
```
So it seems like it can't resolve the path when the wildcard is empty.

eslint config:
```json
{
  ...
  "settings": {
    "import/parser": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    },
    "import/resolver": {
      "typescript": {}
    }
  }
}
```

**Comment by JounQin** [comment]
Can you provide a runnable reproduction so that I can help to debug?

**Comment by JounQin** [comment]
We're using [`tsconfig-paths`](https://github.com/dividab/tsconfig-paths) inside for resolving paths, so please post issue to the original project instead.

Sorry for it.
