### ISSUE TITLE
Plugin fails if no baseUrl is supplied

### ISSUE THREAD

**Issue by bradzacher** [alexgorbatchev/eslint-import-resolver-typescript#6]
originally reported by @jhnns
https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/2#issuecomment-432621629

---

After upgrading to 1.1.0 I get these errors in every file:

Resolve error: Unable to find tsconfig in /my/project/path: Missing baseUrl in compilerOptions  import/no-unresolved
When I set...

"baseUrl": ".",
this plugin works fine. The problem is, however, that VSCode now generates paths on auto import that webpack and Node.js are not able to resolve:

// Instead of
import something from "../../shared/something";
// I get
import something from "src/shared/something";
I'm not sure if VSCode auto import is doing the right thing here, but I also think that baseUrl doesn't have to be set if I'm not using the paths option.

**Comment by jhnns** [comment]
Thank you, works like a charm ✨ 👍
