### ISSUE TITLE
Works but really slow

### ISSUE THREAD

**Issue by yyynnn** [alexgorbatchev/eslint-import-resolver-typescript#60]
Hi there!

i5 ThinkPad taking off like 747
It takes around 10s to save a file

**Comment by JounQin** [comment]
What makes you thinking it's caused by this resolver instead of other tools?

**Comment by yyynnn** [comment]
@JounQin well, I turn it on === it stutters
turn it off === no stuttering 

I will try to reduce the config to trace this issue.

**Comment by TylorS** [comment]
I'm definitely experiencing the same thing described above by the OP. Is there any kind of debug information that would be useful in this case?

**Comment by JounQin** [comment]
Try `DEBUG=eslint-import-resolver-typescript eslint .` to see the debug info first?

**Comment by JounQin** [comment]
Close due to inactive. Please provide more useful information next time.

**Comment by JounQin** [comment]
May be related to https://github.com/dividab/tsconfig-paths/issues/72

**Comment by binarious** [comment]
Same here. The lookup takes between 200 and 900 ms per import statement - which can sum to quite an amount of time in larger projects.

**Comment by JounQin** [comment]
> May be related to [dividab/tsconfig-paths#72](https://github.com/dividab/tsconfig-paths/issues/72)

@binarious Check instead
