### ISSUE TITLE
`import/no-duplicates` warn for duplicates imports from `.d.ts` file

### ISSUE THREAD

**Issue by Kerumen** [alexgorbatchev/eslint-import-resolver-typescript#61]
I'm using [date-fns](https://date-fns.org/) and importing several helpers from the library:

```ts
import format from "date-fns/format";
import parseISO from "date-fns/parseISO";
import getUnixTime from "date-fns/getUnixTime";
```

With the rule `import/no-duplicates` enabled, I have this error:

```
'~/node_modules/date-fns/typings.d.ts' imported multiple times
```

I'm using the library properly and don't have duplicates so I guess it's a bug in the resolver no?

**Comment by JounQin** [comment]
See https://github.com/benmosher/eslint-plugin-import/issues/1479
