### ISSUE TITLE
Cannot resolve estree types

### ISSUE THREAD

**Issue by benmccann** [alexgorbatchev/eslint-import-resolver-typescript#62]
**Steps to reproduce**

This repo is setup with `pnpm`, which helps putting multiple packages in a single repo. You can install with `npm install -g pnpm` if you don't have it already.

```
git clone git@github.com:benmccann/plugins.git
cd plugins
git checkout pluginutils-eslint
pnpm install
cd packages/pluginutils
pnpm lint
```

**Actual results**

>packages/pluginutils/src/extractAssignedNames.ts
  7:8  error  Unable to resolve path to module 'estree'  import/no-unresolved

**Expected results**

I'd expect this to pass linting since the root directory contains an `node_modules/@types/estree/index.d.ts` file with the types.

Maybe it doesn't work when there's only types and not the actual `.js` code? Or maybe it doesn't know how to look in the `node_modules` of parent directories? Or maybe I just messed something up in the setup?

**Comment by JounQin** [comment]
Have you tried `alwaysTryTypes` option?

**Comment by benmccann** [comment]
Yes, that's in my config: https://github.com/benmccann/plugins/blob/44bf678df788d4985aa7970757948ff11de7830f/.eslintrc.js#L16

**Comment by JounQin** [comment]
There are two `typescript` keys in your config, which makes the first one being overridden, what means `alwaysTryTypes` is actually not working.

**Comment by benmccann** [comment]
Ah, thanks!! I've sent a PR to clarify the docs about this point: https://github.com/alexgorbatchev/eslint-import-resolver-typescript/pull/63
