### ISSUE TITLE
Won't work with custom modules

### ISSUE THREAD

**Issue by ddiegosr** [alexgorbatchev/eslint-import-resolver-typescript#65]
In my project I have some custom modules(a module @env for example, to use the [react-native-dotenv](https://github.com/goatandsheep/react-native-dotenv) package).
In VS Code the typescript recognize my module, and provide types and code completion, but when i try to import from this module, i'm still having `import/no-unresolved` being reported by ESLint.

I added this to my eslintrc:
```javascript
  settings: {
    'import/resolver': {
      typescript: {}
    },
  },
```

**Comment by JounQin** [comment]
Out of scope

Try https://github.com/tleunen/eslint-import-resolver-babel-module instead.
