### ISSUE TITLE
Cannot resolve imports in typeRoots

### ISSUE THREAD

**Issue by AleksaC** [alexgorbatchev/eslint-import-resolver-typescript#76]
The plugin does not seem to be able to resolve imports under `node_modules/@types` and unlike node resolver I cannot add paths to make it work.

For example installing `@types/aws-lambda` and then using something like this produces `no-unresolved` error:

```typescript
import type { Handler } from "aws-lambda";

export const handler: Handler = async () => {
  console.log("Hello world");
};
```

**Comment by JounQin** [comment]
Please provide a minimal reproduction. This is the key feature of this resolver in v2.

Make sure this resolver takes higher priority than others.

**Comment by AleksaC** [comment]
Here it is: https://github.com/AleksaC/eslint-typescript-resolver-example.

I didn't know that there can be multiple resolvers but now that you mentioned it I tried this and it worked:
```javascript
  settings: {
    "import/resolver": {
      typescript: {},
      node: {
        extensions: [".ts"],
        paths: ["node_modules/@types"]
      }
    },
  },
```

**Comment by JounQin** [comment]
@AleksaC This is because you didn't have `aws-lambda` installed, if this is intended, you should use `alwaysTryTypes` of this resolver.

```json
{
  "settings": {
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true
      }
    }
  }
}
```
