### ISSUE TITLE
isCore check happens too early

### ISSUE THREAD

**Issue by markjm** [alexgorbatchev/eslint-import-resolver-typescript#81]
There are a collection of npm packages with the same name as node packages
https://www.npmjs.com/package/os
https://www.npmjs.com/package/events

When resolving, we _first_ check if its core, then try to resolve if it isn't. Since these packages have core module names, they are marked as core, even though the actual code may be requiring them from modules directories.

Fix seems simple (move isCore check later in the resolve process), but is a breaking change, so not sure how you want to deal with that.

**Comment by JounQin** [comment]
I imagine these packages works just same as core modules, aren't they?

**Comment by markjm** [comment]
It seems most of them are "shims" for node packages that can work in browser (or visa versa). So yea, in most cases you may not see a difference. One place that you will though:

If you are using the `events` package and import it without declaring it in package.json, the `no-extraneous-dependency` rule will improperly pass
https://github.com/import-js/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md

**Comment by JounQin** [comment]
I'm not sure to understand, `events` is a core module, and we've returned `{ found: true, path: null }` for core modules.

@ljharb Is this expected?

**Comment by JounQin** [comment]
@markjm Or we can provide a new option to enable this feature with disabled by default, so that it won't be a breaking change.

If you're interested, PR welcome.

**Comment by ljharb** [comment]
In node, it's impossible to import/require a core module name and get it from node_modules, unless you have a trailing slash.

In other words, `events` is ALWAYS a core module, no exceptions, but `events/` would pull from node_modules. In other words, the linter warning is correct.

**Comment by markjm** [comment]
Makes sense. Thanks for clarifying!

**Comment by ljharb** [comment]
Since these packages are indeed browser shims, typically bundlers will transparently use the ones in node_modules when bundling, but in node/tests/linting, you're pulling the node core module.

**Comment by JounQin** [comment]
So this issue can be closed, right?

**Comment by markjm** [comment]
Yea, I think this can be closed. Maybe for other custom resolvers it would make sense to make this configurable, but it doesnt seem particularly important/impactful

**Comment by ljharb** [comment]
A custom resolver that runs before the node resolver should certainly be able to do that.
