### ISSUE TITLE
Allow resolving .js module path endings to .ts equivalent

### ISSUE THREAD

**Issue by patrickarlt** [alexgorbatchev/eslint-import-resolver-typescript#82]
Moving this from https://github.com/import-js/eslint-plugin-import/issues/2111#issuecomment-915663474 after https://github.com/import-js/eslint-plugin-import/issues/2111#issuecomment-915663474.

It looks like this was previously discussed in https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/80 and it was requested that an issue get filed in `eslint-plugin-import`. https://github.com/import-js/eslint-plugin-import/issues/2111 discusses this but it was recommended that this functionality move to `eslint-import-resolver-typescript`.

Below is my original comment from the `eslint-plugin-import` issue slightly modified for clarity.

---

I'm migrating a large project written in TypeScript to output native ESM modules for Node. This requires all the `import` statements in TypeScript to end in `.js` so they get output with the `.js` extensions and I would like to lint that import statements of file paths end in `.js`.

I don't think TypeScript is going to budge on their treatment of extensions, see https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937, neither will Node JS back off of required extensions for ESM so it is perfectly valid TypeScript to write this if you are compiling to ESM for Node:

```ts
// foo.ts
export const foo = 'foo';

// bar.ts
import { foo } from './foo.js';
```

Compiles to:

```js
// foo.js
export const foo = 'foo';

// bar.js
import { foo } from './foo.js';
```

Currently this config produces `Missing file extension "ts" for "./foo.js"` which is illogical since TypeScript doesn't actually support `.ts` on file paths https://github.com/microsoft/TypeScript/issues/37582.

```js
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: "module"
  },
  plugins: ["@typescript-eslint", "import"],
  extends: ["plugin:import/recommended", "plugin:import/typescript"],
  rules: {
    "import/extensions": ["error", "ignorePackages"]
  },
  settings: {
    "import/extensions": [".js", ".jsx"],
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    },
    "import/resolver": {
      typescript: {
        project: "./"
      }
    }
  }
};
```

**Comment by JounQin** [comment]
It's supported already https://github.com/alexgorbatchev/eslint-import-resolver-typescript/pull/56

**Comment by JounQin** [comment]
Just remove "import/extensions" this setting.

This resolver resolves the `.ts` file correctly, but it's not allowed in your configuration.

**Comment by patrickarlt** [comment]
Thanks @JounQin! I was able to get this working but I had to REMOVE `typescript` from the `settings.import/resolver`. Am I just missing the point of what `eslint-import-resolver-typescript` is supposed to do? I can push up the minimal reproduction I made if you want.

#### Failure `bar.ts` should pass

![2021-09-09_12-22-27](https://user-images.githubusercontent.com/378557/132749711-c9087331-0a23-473b-8148-45f1cfa842d1.png)

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": [
    "import"
  ],
  "rules": {
    "import/extensions": ["error", "ignorePackages"]
  },
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [
        ".ts",
        ".tsx"
      ]
    },
    "import/resolver": {
      "typescript": {
        "project": "./tsconfig.json"
      }
    }
  }
}
```

#### Success only `baz.ts` fails

![2021-09-09_12-22-14](https://user-images.githubusercontent.com/378557/132749724-6dd7916f-8eff-4513-bdcd-e3a771db3804.png)

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": [
    "import"
  ],
  "rules": {
    "import/extensions": ["error", "ignorePackages"]
  },
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [
        ".ts",
        ".tsx"
      ]
    }
  }
}
```

**Comment by steve-taylor** [comment]
In my case, I also found it necessary to remove `"plugin:import/recommended"` from `"extends"`.

**Comment by lifeiscontent** [comment]
@JounQin this is not done, the PR that you linked doesn't support the option to force an extension like `.js` that points to `.ts`, or `.tsx`
