### ISSUE TITLE
Support leading slashes in `paths`

### ISSUE THREAD

**Issue by qmg-akara** [alexgorbatchev/eslint-import-resolver-typescript#86]
Hello, thanks for this great work!

We have some special aliases that starts with a leading slash, such as `/opt/nodejs/lambda-layer` and `tsc` successfully compiles this code however we are getting `import/no-unresolved` error for these aliases. When we remove the leading slash, i.e. `opt/nodejs/lambda-layer`, it works fine. 

`tsconfig.eslint.json`:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "/opt/nodejs/lambda-layer": ["./packages/lambdaLayer/src"]
    }
  },
  "include": ["**/*.ts"],
  "exclude": ["**/node_modules"]
}
```

error:
`Unable to resolve path to module '/opt/nodejs/lambda-layer'  import/no-unresolved`

`tsc --build` builds the code successfully so I wonder if this is a bug in `eslint-import-resolver-typescript` or am I missing something? Thanks

**Comment by JounQin** [comment]
[tsconfig-paths](https://github.com/dividab/tsconfig-paths) is used under the hood.

**Comment by qmg-akara** [comment]
Thanks @JounQin for the prompt reply! and the link. As this is a [tsconfig-paths](https://github.com/dividab/tsconfig-paths) issue I'm going to close this. Thanks

**Comment by qmg-akara** [comment]
Or I'm opening for tracking [the tsconfig-paths issue](https://github.com/dividab/tsconfig-paths/issues/128), so once it is resolved, `eslint-import-resolver-typescript` could upgrade tsconfig-paths. Feel free to close if you think no need to keep this open.

**Comment by JounQin** [comment]
@qmg-akara You can try to use [patch-package](https://github.com/ds300/patch-package) and patch tsconfig-paths by editing [lib/try-path.js](https://unpkg.com/browse/tsconfig-paths@3.12.0/lib/try-path.js) like https://github.com/dividab/tsconfig-paths/pull/180/files temporarily.

**Comment by qmg-akara** [comment]
Thanks @JounQin for letting me know that! I think we'll just disable `import/no-unresolved` for now until it is resolved. Thanks

**Comment by qmg-akara** [comment]
Hi @JounQin , looks like [tsconfig-paths issue](https://github.com/dividab/tsconfig-paths/issues/128#issuecomment-984553531) is resolved, would it be possible to update this package too? Thanks

**Comment by JounQin** [comment]
We use `"tsconfig-paths": "^3.9.0"`, so it's free to upgrade `tsconfig-paths` to `3.14+` by yourself.

**Comment by qmg-akara** [comment]
Looks like there is no an official way of [upgrading indirect dependencies](https://github.com/yarnpkg/yarn/issues/4986), I have created a PR [here](https://github.com/alexgorbatchev/eslint-import-resolver-typescript/pull/96)

**Comment by JounQin** [comment]
You can delete it from `yarn.lock` or something else, or just reinstall this resolver.
