### ISSUE TITLE
Module resolution issue

### ISSUE THREAD

**Issue by bukharov** [alexgorbatchev/eslint-import-resolver-typescript#87]
We have a monorepo with several applications and some files have identical names. The resolver picks an incorrect file and it gets marked as `external` which interferes with other `import` rules. 

For instance there's `applications/employer/Application.tsx` that imports `Application.actions.ts` which is in the same folder.
When `eslint-plugin-import` invokes this resolver it provides the following arguments:
`modulePath` = `Application.actions`
`sourceFile` = `/applications/employer/Application.tsx`

Then the import gets resolved to : `/applications/admin/Application.actions`. 
Which is from a different application.

Here's my settings object:
```
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
        project: ['applications/*/tsconfig.json'],
      },
    },
```

And some logs:
```
eslint-import-resolver-typescript looking for: Application.actions +1ms
eslint-import-resolver-typescript found multiple matching ts paths: [
  '/applications/admin/Application.actions',
  '/applications/employer/Application.actions'
] +0ms
eslint-import-resolver-typescript matched ts path: /applications/admin/Application.actions +1ms
eslint-import-resolver-typescript matched node path: /applications/admin/Application.actions.ts +0ms
```

Is this a bug or I'm doing something wrong? I believe it should pick the "closest" `tsconfig.json` to the source file rather than picking the first in the list.

**Comment by JounQin** [comment]
Maybe you should use overrides to split the projects instead.

```js
module.exports = {
  overrides: ['admin', 'employer'].map(folder => ({
    filename: `applications/${folder}/**/*`,
    settings: {
      'import-resolver': {
        typescript: {
          project: `applications/${folder}`
        }
      }
    }
  }))
}
```

**Comment by JounQin** [comment]
Close due to inactive.

**Comment by 6XGate** [comment]
This still is not fixed, why was it closed?

**Comment by mizi-lin** [comment]
> 

the same

**Comment by daix6** [comment]
same issue
