### ISSUE TITLE
Local module definition causes `import/order` to interpret as `internal`

### ISSUE THREAD

**Issue by mikestopcontinues** [alexgorbatchev/eslint-import-resolver-typescript#88]
I defined a type for an external module in `/@types/string-hash-64.d.ts`

```ts
declare module 'string-hash-64' {
  export default function stringHash(str: string): number;
}
```

Now, when I try to import it, I get the following error:

```ts
import stringify from 'fast-safe-stringify'; // import/order: There should be at least one empty line between import groups.
import stringHash from 'string-hash-64';
```

Given the following config for `import/order`:

```ts
const orderOpts = {
  'newlines-between': 'always',

  'groups': [
    'external',
    'internal',
    'unknown',
  ],
};
```

It seems to be marking the package as `internal` now. I'm not sure exactly why it's happening with this package. I've defined others without this issue creeping in.

**Comment by JounQin** [comment]
Please provide a runnable reproduction.

It seems like a `eslint-plugin-import` question instead of this resolver. The resolver only helps to resolve the module, but has nothing to do with the `order`.

**Comment by mikestopcontinues** [comment]
Thanks. I'll dig deeper and take it up there if I can create a repro. :)

**Comment by VincentMolinie** [comment]
I got the exact same issue. I had `import/order` for a while now and it's working well.
I just installed this package and all my files import are reordered because some of them are considered as internal.
@mikestopcontinues did you found a solution to your problem?

**Comment by mikestopcontinues** [comment]
Hey, I did get it working at some point. I'm not sure what I did though. Here's any relevant config:

```
  settings: {
    'import/external-module-folders': ['node_modules'],
    'import/internal-regex': '^@cat/',
    'import/resolver': {
      node: true,
    },
  },
```

```
    'import/order': [
      1,
      {
        'alphabetize': {order: 'asc', orderImportKind: 'asc'},
        'distinctGroup': false,
        'newlines-between': 'always',
        'pathGroupsExcludedImportTypes': ['builtin', 'type'],
        'warnOnUnassignedImports': true,
        'groups': [
          'type',
          'builtin',
          'external',
          'internal',
          ['parent', 'sibling', 'index'],
          'object',
          'unknown',
        ],
        'pathGroups': [
          {
            pattern: '**/*.css',
            group: 'unknown',
            position: 'after',
          },
        ],
      },
    ],
```
