### ISSUE TITLE
not work ?

### ISSUE THREAD

**Issue by macheteHot** [alexgorbatchev/eslint-import-resolver-typescript#89]
![image](https://user-images.githubusercontent.com/26652329/147878017-5789d054-2002-470f-b56f-875357f4decc.png)

the workspace is look like 
![image](https://user-images.githubusercontent.com/26652329/147878047-5e15ec86-29b8-465f-bfa9-8e0bc4455e2d.png)

**Comment by JounQin** [comment]
Duplicate of #71

**Comment by macheteHot** [comment]
thank a lot
