### ISSUE TITLE
Can't resolve timers/promises

### ISSUE THREAD

**Issue by pikeas** [alexgorbatchev/eslint-import-resolver-typescript#90]
```
import {setTimeout} from "timers/promises"
```

```
Resolve error: typescript with invalid interface loaded as resolver eslint(import/no-duplicates)
```

I'm also unable to disable the error with `// eslint-disable-line`

**Comment by JounQin** [comment]
Please provide a runnable reproduction.

**Comment by pikeas** [comment]
I'm having some trouble reproducing it from scratch. I did find a clue:

```
module.exports = {
    [...]
    settings: {
        "import/resolver": {
            node: {
                extensions: [".js", ".ts"],
            },
            typescript: {},
        },
    },
}
```

If I comment out `typescript: {}`, the error goes away. Somehow, when the value is set to an empty hash, it trips up the resolver.

**Comment by JounQin** [comment]
Without a runnable reproduction, I can't imagine what is going on, sorry.

**Comment by JounQin** [comment]
Duplicate with https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/93

See also https://github.com/inspect-js/is-core-module/blob/main/core.json#L117
