### ISSUE TITLE
Eslint not recognizing alias path

### ISSUE THREAD

**Issue by harikautilya** [alexgorbatchev/eslint-import-resolver-typescript#95]
Hello,
I am trying to create a project with `react-app-rewired` with alias path. The project works fine but having trouble with the alias lints as the eslint is unable to identify the alias
**tsconfig.json**
```
{
  "extends": "./paths.json",
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "removeComments": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "src"
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**path.json**
```
{
    "compilerOptions": {
        "paths": {
            "@components/*": [
                "src/components/*"
            ],
            "@layouts/*": [
                "src/layouts/*"
            ]
        }
    }
}
```
**eslintrc.js**
```
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: './tsconfig.json',
    tsconfigRootDir: './'
  },
  plugins: [
    '@typescript-eslint',
    'import',
  ],
  rules: {

  },
  settings: {
    'import/resolver': {
      typescript: {
        "alwaysTryTypes": true,
      },
    },
  }
};

```

config-overrides.js

```
const {
  override,
  disableChunk,
  addBabelPlugins,
  removeModuleScopePlugin,
  addBabelPresets,
  addWebpackAlias,
} = require('customize-cra');

const path = require('path')
module.exports = override(
  ...addBabelPresets('@babel/preset-env', '@babel/preset-react'),
  ...addBabelPlugins(
    [
      'import',
      { libraryName: 'antd-mobile', libraryDirectory: 'lib', style: 'css' },
      'antd-mobile',
    ],
    [
      'import',
      { libraryName: 'antd', libraryDirectory: 'lib', style: true },
      'antd',
    ],
  ),
  disableChunk(),
  removeModuleScopePlugin(),
  addWebpackAlias({
    ['@components']: path.resolve(__dirname, 'src/components'),
    ['@layouts']: path.resolve(__dirname, 'src/layouts')
  })
);

```

Thank you for your time

Edit
Repo link : https://github.com/harikautilya/events

**Comment by JounQin** [comment]
Please provide a minimal and runnable reproduction.

**Comment by tleunen** [comment]
I had a very similar issue in a way, and I noticed that `tsconfig-paths` was prepending the alias path with the `baseUrl`. Therefore, if your `baseUrl` is `src`. Try removing `src` from your alias path, such as `"@components/*": ["components/*"]`

**Comment by harikautilya** [comment]
@tleunen got it let me try it today and get back to you
@JounQin will edit the issue soon

**Comment by harikautilya** [comment]
@tleunen Tired it. Didnt not work out.
@JounQin Make my repo public as it does nto contain any important information. 
Will make it private as soon as the issue closes

**Comment by JounQin** [comment]
@harikautilya Your reproduction is too huge, and I didn't know what command to run to reproduce even...

**Comment by JounQin** [comment]
A rough guess:

```jsonc
// paths.json
{
    "compilerOptions": {
        "baseUrl": "src",
        "paths": {
            "@components/*": ["components/*"],
            "@components": ["components"],
            "@layouts/*": ["layouts/*"],
            "@layouts": ["layouts"]
        }
    }
}

```

**Comment by harikautilya** [comment]
@JounQin Oh. 
here are steps.
1. Clone the repo
2. Npm install
3. Npm run start

You should see the following error
`Cannot find module '@layouts' or its corresponding type declarations.`

but the project fine on port `http://localhost:3000/`

**Comment by harikautilya** [comment]
@JounQin The fix you suggested works!!!!

But what is surprising is in tsconfig.json `  "baseUrl": "src" ` does exisit. Any particular reason why this happens only when present in paths.json

**Comment by JounQin** [comment]
> @JounQin Oh. here are steps.
> 
> 1. Clone the repo
> 2. Npm install
> 3. Npm run start
> 
> You should see the following error `Cannot find module '@layouts' or its corresponding type declarations.`
> 
> but the project fine on port `http://localhost:3000/`

This is nothing related to ESLint or this resolver. `@layouts/*` and `@layouts` are different.
