### ISSUE TITLE
Update tsconfig-paths to latest fix

### ISSUE THREAD

**Issue by commit-master** [alexgorbatchev/eslint-import-resolver-typescript#98]
Hi,

Thanks again for this wonderful package. A security vulnerability has been discovered for the `minimist` package. `tsconfig-paths` makes use of it, they have update their package to fix the issue. Could you be so kind and update this package to the latest fix?

More info here: https://github.com/advisories/GHSA-vh95-rmgr-6w4m
`tsconfig-paths` package.json: https://github.com/dividab/tsconfig-paths/blob/master/package.json

Thanks again.

**Comment by JounQin** [comment]
We're using `https://github.com/dividab/tsconfig-paths: "^3.9.0"` which should cover the latest version, if you want to ensure the version of `tsconfig-paths` to be the latest, just reinstall `eslint-import-resolver-typescript`, you'll get it.

See also https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/86#issuecomment-1066435584

**Comment by commit-master** [comment]
Thanks for the quick reply.
I'm currently on `v2.5.0` which seems to be the latest version. 

`tsconfig-paths@3.9.0` is using an old and vulnerable `minimist` dependency (see below)
https://github.com/dividab/tsconfig-paths/blob/287867d1140c14366f280910099938c5c0976f3c/package.json#L33

They just updated this vulnerability fix a few hours ago in the [v3.14.1](https://github.com/dividab/tsconfig-paths/releases/tag/v3.14.1):
https://github.com/dividab/tsconfig-paths/commit/22b9d74abaf5f9fee19b94b008a0e528e73b8bca

Thanks.

**Comment by JounQin** [comment]
Again, `^3.9.0` covers `3.14.1`.

**Comment by commit-master** [comment]
This is very confusing.

Removing the package-lock and node modules and re-installing does not change anything since this is a sub-dependency. Am I missing something here ?

To me the best way to handle this would be updating your dependencies on this project and then running an `npm update` on my end.

I don't think you can currently update a sub-dependency on a project.

I'd be happy to submit a PR for this if you want.

**Comment by JounQin** [comment]
`npm uninstall eslint-import-resolver-typescript && npm install -D eslint-import-resolver-typescript` have you ever tried it? `^3.9.0` will resolve the latest version of `tsconfig-paths` on the new installation.

**Comment by commit-master** [comment]
I did yes, as well as deleting `node_modules` and the `package-lock.json`. After running a `npm audit` the vulnerability is still flagged:

![image](https://user-images.githubusercontent.com/11718935/159674700-d108c0ba-4606-4835-bc27-ec268de46d90.png)

**Comment by JounQin** [comment]
@commit-master `v2.6.0` released.

**Comment by commit-master** [comment]
Thanks a lot !
